### ISSUE TITLE
Just a friendly making-aware-of

### ISSUE THREAD

**Issue by phoekjelle** [ArchLinux-Development/ArchLinux-Install-Scripts#1]
Dear mister @Eliminater74,

I tried to make your install_arch_btrfs.sh script usable with nvme-chips. I didn't get further than trying… But, the reason I send you this issue is to make you aware of the Nvme-chip.

* HDD on linux are:
/dev/hda1
* SSD on linux are:
 /dev/sda1
* Virtual drives on linux are:
/dev/vda1
* But NVME drives on linux are:
/dev/nvme0n1**p1**

Thank you.

**Comment by Eliminater74** [comment]
Thank you for your comment, I will take that into consideration but for now, I havent messed with this project much since my current Arch Linux setup, Mobo died and just now waiting on a new mobo to continue the project.. I am also working on some VR Projects, Dont have as much time as I did previous.. but thank you for your comment..

**Comment by phoekjelle** [comment]
Don't worry. 
Who is Mobo, or do I interpret it wrong.
I didn't meant to pouch you 'back to work' or something, I just wanted to share some information. 
Have fun with your VR Projects! Sounds intresting!
